const SURVEYS = [
  {
    id: 'ems-ci',
    title: '救護實習臨床指導員影響力調查',
    titleEn: 'EMS Clinical Preceptor Impact Survey',
    desc: '探討臨床指導員對救護人員養成之關鍵影響 · 中文 / English · IRB: ECKIRB1150307',
    url: 'https://script.google.com/macros/s/AKfycbx8WdCYc_q2b1w0zs3UabnmYNLQd6Pc-sLlGrscRnt1iIWsvI2lodXS-uARhCqgaTMPrg/exec',
    status: 'active',
    start: '2026/05/30',
    end: '2026/06/30',
    icon: 'ti-stethoscope',
    lang: '中 / EN',
  },
  {
    id: 'ems-dnr',
    title: 'EMS DNR 相關調查',
    titleEn: 'EMS DNR Survey',
    desc: '救護現場 DNR 執行相關議題調查· 多語言 · IRB: ECKIRB1150308',
    url: 'https://script.google.com/macros/s/AKfycbzL9yXMADWUZXdO6TCBUMqtI4mlUST6UmIvCn3VZZ1K67Qk-ts4jziGMHJhGeRCUm4_Mg/exec',
    status: 'active',
    start: '2026/05/30',
    end: '2026/06/30',
    icon: 'ti-file-description',
    lang: '中文',
  },
  {
    id: 'ems-mental',
    title: 'EMS 救護員心理健康調查',
    titleEn: 'EMS Provider Mental Health Survey',
    desc: '探討救護員心理健康與職業壓力現況· 中文 · IRB: ECKIRB1150105',
    url: 'https://tally.so/r/Bzdy27',
    status: 'active',
    start: '2026/04/01',
    end: '2026/06/30',
    icon: 'ti-brain',
    lang: '中文',
  },
];